namespace System.Reflection.Metadata.ILReader
{
  public enum Opcode : byte
  {
    /// <summary>Adds two values and pushes the result onto the evaluation stack.</summary>
    Add = 0,
    /// <summary>Adds two integers, performs an overflow check, and pushes the result onto the evaluation stack.</summary>
    AddOvf = 1,
    /// <summary>Adds two unsigned integer values, performs an overflow check, and pushes the result onto the evaluation stack.</summary>
    AddOvfUn = 2,
    /// <summary>Computes the bitwise AND of two values and pushes the result onto the evaluation stack.</summary>
    And = 3,
    /// <summary>Returns an unmanaged pointer to the argument list of the current method.</summary>
    Arglist = 4,
    /// <summary>Transfers control to a target instruction if two values are equal.</summary>
    Beq = 5,
    /// <summary>Transfers control to a target instruction if the first value is greater than or equal to the second value.</summary>
    Bge = 6,
    /// <summary>Transfers control to a target instruction if the first value is greater than the second value, when comparing unsigned integer values or unordered float values.</summary>
    BgeUn = 7,
    /// <summary>Transfers control to a target instruction if the first value is greater than the second value.</summary>
    Bgt = 8,
    /// <summary>Transfers control to a target instruction if the first value is greater than the second value, when comparing unsigned integer values or unordered float values.</summary>
    BgtUn = 9,
    /// <summary>Transfers control to a target instruction if the first value is less than or equal to the second value.</summary>
    Ble = 10,
    /// <summary>Transfers control to a target instruction if the first value is less than or equal to the second value, when comparing unsigned integer values or unordered float values.</summary>
    BleUn = 11,
    /// <summary>Transfers control to a target instruction if the first value is less than the second value.</summary>
    Blt = 12,
    /// <summary>Transfers control to a target instruction if the first value is less than the second value, when comparing unsigned integer values or unordered float values.</summary>
    BltUn = 13,
    /// <summary>Transfers control to a target instruction when two unsigned integer values or unordered float values are not equal.</summary>
    BneUn = 14,
    /// <summary>Converts a value type to an object reference (type O).</summary>
    Box = 15,
    /// <summary>Unconditionally transfers control to a target instruction.</summary>
    Br = 16,
    /// <summary>Signals the Common Language Infrastructure (CLI) to inform the debugger that a break point has been tripped.</summary>
    Break = 17,
    /// <summary>Transfers control to a target instruction if value is false, a null reference (Nothing in Visual Basic), or zero.</summary>
    Brfalse = 18,
    /// <summary>Transfers control to a target instruction if value is true, not null, or non-zero.</summary>
    Brtrue = 19,
    Call = 20,
    Calli = 21,
    Callvirt = 22,
    Castclass = 23,
    Ceq = 24,
    Cgt = 25,
    CgtUn = 26,
    Ckfinite = 27,
    Clt = 28,
    CltUn = 29,
    Constrained = 30,
    Conv = 31,
    ConvOvf = 32,
    ConvOvfUn = 33,
    ConvUn = 34,
    Cpblk = 35,
    Cpobj = 36,
    Div = 37,
    DivUn = 38,
    Dup = 39,
    Endfilter = 40,
    Endfinally = 41,
    Initblk = 42,
    Initobj = 43,
    Isinst = 44,
    Jmp = 45,
    Ldarg = 46,
    Ldarga = 47,
    LdcI4 = 48,
    LdcI8 = 49,
    LdcR4 = 50,
    LdcR8 = 51,
    Ldelem = 52,
    Ldelema = 53,
    LdelemRef = 54,
    Ldfld = 55,
    Ldflda = 56,
    Ldftn = 57,
    Ldind = 58,
    LdindRef = 59,
    Ldlen = 60,
    Ldloc = 61,
    Ldloca = 62,
    Ldnull = 63,
    Ldobj = 64,
    Ldsfld = 65,
    Ldsflda = 66,
    Ldstr = 67,
    Ldtoken = 68,
    Ldvirtftn = 69,
    Leave = 70,
    Localloc = 71,
    Mkrefany = 72,
    Mul = 73,
    MulOvf = 74,
    MulOvfUn = 75,
    Neg = 76,
    Newarr = 77,
    Newobj = 78,
    Nop = 79,
    Not = 80,
    /// <summary>Compute the bitwise complement of the two integer values on top of the stack and pushes the result onto the evaluation stack.</summary>
    Or = 81,
    Pop = 82,
    Prefix1 = 83,
    Prefix2 = 84,
    Prefix3 = 85,
    Prefix4 = 86,
    Prefix5 = 87,
    Prefix6 = 88,
    Prefix7 = 89,
    Prefixref = 90,
    Readonly = 91,
    Refanytype = 92,
    Refanyval = 93,
    Rem = 94,
    RemUn = 95,
    Ret = 96,
    Rethrow = 97,
    Shl = 98,
    Shr = 99,
    ShrUn = 100,
    Sizeof = 101,
    Starg = 102,
    Stelem = 103,
    StelemRef = 104,
    Stfld = 105,
    Stind = 106,
    StindRef = 107,
    Stloc = 108,
    Stobj = 109,
    Stsfld = 110,
    Sub = 111,
    SubOvf = 112,
    SubOvfUn = 113,
    Switch = 114,
    Tail = 115,
    Throw = 116,
    Unaligned = 117,
    Unbox = 118,
    UnboxAny = 119,
    Volatile = 120,
    /// <summary>Computes the bitwise XOR of the top two values on the evaluation stack, pushing the result onto the evaluation stack.</summary>
    Xor = 121
  }
}